### ISSUE TITLE
Support for illuminate/support 9

### ISSUE THREAD

**Issue by enderandpeter** [renoki-co/aws-elastic-client#46]
# The Issue

Thank you very much for making this tool. It is being used in a Laravel 8 application that I want to upgrade to Laravel 9. There is an error when running `composer update`

# Expected Behavior

When upgrading a project from Laravel 8 to 9, this package will still be supported.

# Actual Behavior

When upgrading from Laravel 8 to 9 via `composer update`, the following problem is reported:

```
renoki-co/aws-elastic-client 1.2.0 requires illuminate/support ^7.0|^8.0 -> satisfiable by illuminate/support[v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev].
- Only one of these can be installed: illuminate/support[v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev], laravel/framework[v9.11.0, ..., 9.x-dev]. laravel/framework replaces illuminate/support and thus cannot coexist with it.
```

# Notes

I was looking at the source code and tests for this utility and I was not seeing anything that blocked it from working in Laravel 9, so I am hoping that `illuminate/support:^9.0` can be added to the `composer.json`.

I noticed the [ci.yml workflow](https://github.com/renoki-co/aws-elastic-client/blob/master/.github/workflows/ci.yml). If I fork this project, I hope I can add a matrix for Laravel 9, not to mention a later version of PHP, and that everything will pass. Assuming it will let me run these actions...

Was anyone aware of issues this tool has with Laravel 9 and/or PHP 8.1?

**Comment by rennokki** [comment]
Just tagged 1.3.0
